// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxp8VL-T7WslRqgDP0svpVNPfqloSfwts',
    appId: '1:784665362923:web:4115e3a0a1f8d0597f99ae',
    messagingSenderId: '784665362923',
    projectId: 'ecgo-new-apps',
    authDomain: 'ecgo-new-apps.firebaseapp.com',
    storageBucket: 'ecgo-new-apps.appspot.com',
    measurementId: 'G-N4E09519ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0wQyKUlaq0RzQ1rWaJgYfAzN84byeOY',
    appId: '1:784665362923:android:73982783da1b49e27f99ae',
    messagingSenderId: '784665362923',
    projectId: 'ecgo-new-apps',
    storageBucket: 'ecgo-new-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQdCMM96j2cZJ4WWB4tJqvHdlg69aOXvc',
    appId: '1:784665362923:ios:37f87413abc70a987f99ae',
    messagingSenderId: '784665362923',
    projectId: 'ecgo-new-apps',
    storageBucket: 'ecgo-new-apps.appspot.com',
    iosBundleId: 'com.evmoto.user.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQdCMM96j2cZJ4WWB4tJqvHdlg69aOXvc',
    appId: '1:784665362923:ios:fe7be02752ee85877f99ae',
    messagingSenderId: '784665362923',
    projectId: 'ecgo-new-apps',
    storageBucket: 'ecgo-new-apps.appspot.com',
    iosBundleId: 'com.example.newEvmotoUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxp8VL-T7WslRqgDP0svpVNPfqloSfwts',
    appId: '1:784665362923:web:4115e3a0a1f8d0597f99ae',
    messagingSenderId: '784665362923',
    projectId: 'ecgo-new-apps',
    authDomain: 'ecgo-new-apps.firebaseapp.com',
    storageBucket: 'ecgo-new-apps.appspot.com',
    measurementId: 'G-N4E09519ZV',
  );

}